version: "15.1"
services:
  dev-postgres:
    container_name: postgres.local
    image: postgres:15.1-alpine
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin